[phases.setup]
nixPkgs = [
  "python39",
  "gcc"
]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["python backend/manage.py collectstatic --noinput"]

[start]
cmd = "python backend/manage.py migrate && cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
