[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "gcc"
]

[phases.install]
cmds = [
  "python3.9 -m pip install --upgrade pip",
  "python3.9 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python3.9 manage.py collectstatic --noinput"]

[start]
cmd = "python3.9 manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
